spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    enable
  jwt:
    secret-access-token: 61a8d20dd4dc8047f65ef5eeec6c51bcf83ce17e6c50defc3bba00fccb6858ad
    secret-refresh-token: df45e8e2e54ab8d0a9d2a8a82fb48765bdce1db29d8718f413296fcc9d08c2c0
  datasource:
    url: jdbc:mysql://summar.cv9xsydusdbz.ap-northeast-2.rds.amazonaws.com:3306/summar?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: summarmysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: 13.209.114.45
    port: 6379
    password: summarredis
springdoc:
  swagger-ui:
    path: /summar-api-doc.html
    operations-sorter: method
    disable-swagger-default-url: true
    enabled: true
  api-docs:
    enabled: true

application:
  aws:
    accessKey: AKIA3AI73FTRVWWXC2P4
    secretKey: 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
    s3Bucket: image.summar.io
elasticsearch:
  host: 13.209.114.45
  port: 9200

push:
  server-key: key=AAAAB9uCHb0:APA91bF7WLRRj7XDry8O34cmO3tbsjZfcARgA4AT38H32g0Yr_310AlLK7KExHC_XkQwSEQtpIW6-aiLz3d_veyDFmJb_vl1w34xxcmDQEnnH-fK_PQmGIJjrhyEv9FlGTVdnw60N3FE
  device-key: e8JYHSQQyUabgu1g55CCNK:APA91bEh752UcgpOy8NYF41LC6aQ0g3PSvKqrlONWfS_S6Z9tIBmKbxAY5oQNOOMK4pZqxvs-Rl6yNFgdDS8R3w6t2wE-PXmvqZ0H8Fc-3SdliQvHUoHLpwRcfXf9rJ57aueioviqSJA
